version: "3"
services:
  db:
    build: ./db/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/tmp/db:/var/lib/mysql
  api:
    build: ./api/
    command: bash -c "cd ~/../myapp && rails s -b 0.0.0.0"
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    stdin_open: true
